[build]
  command = "npm run build"
  publish = "dist/ssr/client"

[functions]
  directory = "dist/ssr/server"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
