build_app:
  stage: build
  image: node:24
  dependencies:
    - install_dependencies
  script:
    - npm run build
    - tar -czf starlight-tech-radar-build.tar.gz dist/
  artifacts:
    paths:
      - dist/
      - starlight-tech-radar-build.tar.gz
    expire_in: 1 hour
